### ISSUE TITLE
Eligibility - we need our own types

### ISSUE THREAD

**Issue by dvanic** [nrmay/TeSS#13]
![image](https://user-images.githubusercontent.com/3272378/114667927-6d79ca80-9d43-11eb-8166-7bf17193d5b1.png)

Current eligibility doesn't match our user stories. I could see eligibility

- [ ] Limited to host university only (maybe? list universities individually, but could get loooong)
- [ ] Limited to Intersect members
- [ ] Limited to QCIF members
- ...
- [ ] Open to all, first come/first serve
...

**Comment by dvanic** [comment]
Also, @nrmay sorry - I can't edit labels after assignment, so this isn't a bug but a feature request...

**Comment by burkemlou** [comment]
Maybe eligibility is the wrong word for this drop down. Could it be something like 'Application process'?

We need to keep:
- Expression of interest
- First come, first served
- By invitation

Eligibility could then be something like
- Limited to staff/students at host organisation
- Limited to QCIF member organisations 
- Limited to Intersect member organisations
- Open to all
- etc

**Comment by nrmay** [comment]
Done. Sprint 3.
Dictionary of eligibility options can now be updated and switched as required.
Each options includes a title (as the option) and description (shown when mouse hovers over the option).
