### ISSUE TITLE
Use of the word TeSS in Subscribe - add to calendar

### ISSUE THREAD

**Issue by KathrynU** [nrmay/TeSS#213]
Message at the bottom of the pop-up window states - Please note, it may take a while for newly-created events in TeSS to synchronize with your Google Calendar. 

Should be DReSA instead of TeSS. Also change to synchronise. Is there a need for the hyphen between newly-created?
<img width="310" alt="Screenshot 2021-09-10 105931" src="https://user-images.githubusercontent.com/81134144/132782328-fdfcd94c-f1b8-4cf3-b6a4-c13ef34a3464.png">

**Comment by nrmay** [comment]
@KathrynU I can see how to fix it, but I can't get the pop-up window to appear.
Please, include steps to reproduce.

**Comment by nrmay** [comment]
@KathrynU  No problem. Found the pop-up...
