### ISSUE TITLE
Event type

### ISSUE THREAD

**Issue by burkemlou** [nrmay/TeSS#25]
The current event types drop down doesn't provide enough options.

<img width="807" alt="Screen Shot 2021-04-28 at 1 58 28 pm" src="https://user-images.githubusercontent.com/68895620/116344636-eee45900-a829-11eb-8891-9b0fecf1ace6.png">

At a minimum we would need:
- Webinar
- Workshop
- Conference

Others might be 
- Knowledge exchange
- Hackathon
- Drop-in session/hackyhour

**Comment by nrmay** [comment]
Done. 
Dictionary of event types is not replaceable with DReSA options.
Each options includes a title (shown in the drop down list) and a description (shown when mouse hovers over the option).
