### ISSUE TITLE
Content Providers: add contact email

### ISSUE THREAD

**Issue by nrmay** [nrmay/TeSS#263]
Add a field to the content provider model: contact.
- [x] add to model
- [x] ~~validate email format~~
- [x] add to edit form
- [x] show on Provider details page

Also: fix provider approved editors dropdown list.
- [x] restrict to visible users only
- [x] sort by full or user name

**Comment by KathrynU** [comment]
This could be useful. Even though events and training materials have the contact email (generally providers email).
